"""2

Revision ID: 52085cfce6b6
Revises: 
Create Date: 2022-03-18 18:20:10.431398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52085cfce6b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('token_exp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_exp')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
